# Generated by Django 5.2.7 on 2025-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
